import mongoose from "mongoose"

const ticketSchema = new mongoose.Schema({
    title :  String,
    description : String,
    status : {type : String, default : "TODO"},
    createdBy:{type: mongoose.Schema.Types.ObjectId , ref : "User"}, //linking to database by creating an unique ID 
    //(to "User" which we packaged in user.js file in last line)
    assignedTo : {
        type : mongoose.Schema.Types.ObjectId,
        ref : "User",
        default : null
    },
    priority : String, //the value like priority = "medium" will be generated by AI
    resolvedByAI: { type: Boolean, default: false }, // Track if AI resolved it
    deadline : Date,
    helpfulNotes : String,
    relatedSkills :  [String],
    createdAt : {type : Date, default : Date.now}, 
});

export default mongoose.model("Ticket",ticketSchema);